<?php
namespace Turahe\Master\Models;

use Turahe\Master\Traits\AutoSort;
use Turahe\Master\Traits\AutoFilter;
use Illuminate\Support\Facades\Cache;
use Illuminate\Database\Eloquent\Model as BaseModel;

abstract class Model extends BaseModel
{
    use AutoFilter;
    use AutoSort;
    /**
     * @var string
     */
    protected $keyType = 'string';

    /**
     * @var string[]
     */
    protected $searchableColumns = ['id', 'name'];

    /**
     * Model constructor.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    /**
     * @param $query
     * @param $keyword
     */
    public function scopeSearch($query, $keyword)
    {
        if ($keyword && $this->searchableColumns) {
            $query->whereLike($this->searchableColumns, $keyword);
        }
    }

    /**
     * Bootstrap the model and its traits.
     *
     * Caching model when updating and
     * delete cache when delete models
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function ($instance) {
            Cache::put($this->table.'_'.$instance->name, $instance);
        });
        static::deleting(function ($instance) {
            Cache::forget($this->table.'_'.$instance->name);
        });
    }
}
